import { describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PersistenceService } from './persistence-service';
import { AggregateMutationError } from './aggregate-persistence';
import { JournalAggregateStore } from './journal-aggregate-adapter';

type V = { state: string };
function fixture() { const dir = mkdtempSync(join(tmpdir(), 'iips-agg-')); const journal = new PersistenceService({ dataDir: dir }); const make = () => new JournalAggregateStore<V>(journal, () => '2026-09-16T00:00:00.000Z', (() => { let i = 0; return () => `h-${++i}`; })()); return { dir, journal, make }; }
const mutation = (expectedVersion = 0, key = 'k1', aggregateId = 'a1') => ({ tenantId: 't1', ownerUserId: 'u1', aggregateId, expectedVersion, idempotencyKey: key, mutate: () => ({ state: 'ready' }) });

describe('P13-B bounded journal adapter', () => {
  it('persists records/history and recovers them from the existing journal', () => { const f = fixture(); try { const a = f.make(); a.mutate(mutation()); const b = f.make(); b.recoverScope('t1', 'u1'); expect(b.read('t1', 'u1', 'a1')?.version).toBe(1); expect(b.historyFor('t1', 'u1', 'a1')).toHaveLength(1); } finally { rmSync(f.dir, { recursive: true, force: true }); } });
  it('replays idempotency after reconstruction and conflicts on stale version', () => { const f = fixture(); try { f.make().mutate(mutation()); const b = f.make(); b.recoverScope('t1', 'u1'); expect(b.mutate(mutation()).replayed).toBe(true); expect(() => b.mutate(mutation(0, 'k2'))).toThrowError(AggregateMutationError); } finally { rmSync(f.dir, { recursive: true, force: true }); } });
  it('rejects materially different reuse of an idempotency key before and after restart', () => { const f = fixture(); try { f.make().mutate(mutation()); const b = f.make(); b.recoverScope('t1', 'u1'); expect(() => b.mutate({ ...mutation(0, 'k1'), mutate: () => ({ state: 'different' }) })).toThrowError(AggregateMutationError); } finally { rmSync(f.dir, { recursive: true, force: true }); } });
  it('recovery is repeatable without duplicating history or versions', () => { const f = fixture(); try { const a = f.make(); a.mutate(mutation()); a.mutate(mutation(1, 'k2')); const b = f.make(); b.recoverScope('t1', 'u1'); const before = b.historyFor('t1', 'u1', 'a1'); b.recoverScope('t1', 'u1'); expect(b.historyFor('t1', 'u1', 'a1')).toEqual(before); expect(b.read('t1', 'u1', 'a1')?.version).toBe(2); } finally { rmSync(f.dir, { recursive: true, force: true }); } });
  it('ignores malformed, unknown, and conflicting commit records', () => { const f = fixture(); try { f.journal.append({ tenantId: 't1', ownerUserId: 'u1', dedupKey: 'bad', payload: { kind: 'aggregate.prepare', groupId: 'bad' } }); f.journal.append({ tenantId: 't1', ownerUserId: 'u1', dedupKey: 'unknown', payload: { kind: 'aggregate.commit', groupId: 'unknown', mutationKeys: ['x'] } }); f.journal.append({ tenantId: 't1', ownerUserId: 'u1', dedupKey: 'c1', payload: { kind: 'aggregate.commit', groupId: 'conflict', mutationKeys: ['a'] } }); f.journal.append({ tenantId: 't1', ownerUserId: 'u1', dedupKey: 'c2', payload: { kind: 'aggregate.commit', groupId: 'conflict', mutationKeys: ['b'] } }); const b = f.make(); b.recoverScope('t1', 'u1'); expect(b.read('t1', 'u1', 'a1')).toBeUndefined(); } finally { rmSync(f.dir, { recursive: true, force: true }); } });
  it('commits multi-record groups atomically and ignores incomplete groups', () => { const f = fixture(); try { const a = f.make(); a.mutateMany([{ ...mutation(0, 'k1', 'a1'), groupKey: 'g' }, { ...mutation(0, 'k2', 'a2'), groupKey: 'g' }]); const b = f.make(); b.recoverScope('t1', 'u1'); expect(b.read('t1', 'u1', 'a1')?.version).toBe(1); expect(b.read('t1', 'u1', 'a2')?.version).toBe(1); f.journal.append({ tenantId: 't1', ownerUserId: 'u1', dedupKey: 'incomplete', payload: { kind: 'aggregate.prepare', groupId: 'incomplete', mutation: mutation(1, 'k3', 'a1'), value: { state: 'bad' }, fromVersion: 1, occurredAt: '2026-09-16T00:00:00.000Z', historyId: 'bad' } }); const c = f.make(); c.recoverScope('t1', 'u1'); expect(c.read('t1', 'u1', 'a1')?.version).toBe(1); } finally { rmSync(f.dir, { recursive: true, force: true }); } });
});
